### ISSUE TITLE
[Icon Request] Telegram

### ISSUE THREAD

**Issue by deadbaed** [materialos/CM12-Theme#16]
An icon for telegram is missing :)

**Comment by anuragk47** [comment]
There actually is an icon for telegram already https://github.com/materialos/CM12-Theme/blob/master/theme/src/main/assets/icons/res/drawable-nodpi/telegram.png
Maybe it is too close to stock so you couldn't differentiate .Also, MaterialOS Android Icon Pack is the better place for icon requests since they get straight to Daniel & Co. and I make sure we have all icons from there in the theme. Anyways, you seem to love Telegram (a lot)!

**Comment by deadbaed** [comment]
Oh sorry I didn't know! :)

**Comment by deadbaed** [comment]
Oh sorry I didn't know!
And yea I like Telegram :)
On Dec 24, 2015 3:55 PM, Anurag Kumar notifications@github.com wrote:There actually is an icon for telegram already https://github.com/materialos/CM12-Theme/blob/master/theme/src/main/assets/icons/res/drawable-nodpi/telegram.png
Maybe it is too close to stock so you couldn't differentiate .Also, MaterialOS Android Icon Pack is the better place for icon requests since they get straight to Daniel & Co. and I make sure we have all icons from there in the theme. Anyways, you seem to love Telegram (a lot)!
